### ISSUE TITLE
hi bro please help need ur contribution

### ISSUE THREAD

**Issue by jaisyullah** [juniskane/nokia_x2_rm-1013_2.0.0.11#1]
Hi im from indonesian,

We are nokia fans, but they are didnt share rm-1030 (Nokia XL) kernel source code online to future development.

Could you help our nokia community ?

Warm Regards,
Jaisy

**Comment by juniskane** [comment]
Hi jaisyullah,

Unfortunately cannot help with this. My own formal letters to MMO's Source Code Requests PO box haven't been replied. I requested Nokia XL and Nokia X2 PR2 (later kernel than what is here in my github) kernel sources but never heard back. I guess nobody handles these matters in MMO these days, at least not with any degree of competence. The process of requesting GPL source code has been deliberately made awkward.

Your best bet is to keep writing hand-written letters to MMO exactly as per their instructions, and if no reply, then start complaining to people at gpl-violations.org as MS is clearly pirating the GPLed software if not releasing modifications back to the community.

All the best,
 Juha
